apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: {{ .Values.cyber.roleBinding.name }}
  namespace: {{ .Values.cyber.roleBinding.namespace }}
subjects: 
  - kind: {{ .Values.cyber.roleBinding.subjects.kind }}
    name: {{ .Values.cyber.roleBinding.subjects.name }}
    namespace: {{ .Values.cyber.roleBinding.subjects.namespace }}
roleRef: 
  kind: {{ .Values.cyber.roleBinding.roleRef.kind }}
  name: {{ .Values.cyber.roleBinding.roleRef.name }}
  apiGroup: {{ .Values.cyber.roleBinding.roleRef.apiGroup }}
