apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cyber.deployment.name }}
  namespace: {{ .Values.cyber.deployment.namespace }}
  labels:
    tier: {{ .Values.cyber.deployment.labels.tier }}
    prod: {{ .Values.cyber.deployment.labels.prod }}
  annotations:
    prometheus.io/scrape: {{ .Values.cyber.deployment.annotations.prometheus.io.scrape | quote }}
    prometheus.io/path: {{ .Values.cyber.deployment.annotations.prometheus.io.path }}
    prometheus.io/port: {{ .Values.cyber.deployment.annotations.prometheus.io.port | quote }}
spec:
  replicas: {{ .Values.cyber.deployment.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.cyber.deployment.spec.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.cyber.deployment.spec.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      tier: {{ .Values.cyber.deployment.spec.selector.matchLabels.tier }}
  template:
    metadata:
      labels:
        tier: {{ .Values.cyber.deployment.spec.template.labels.tier }}
    spec:
      serviceAccountName: {{ .Values.cyber.deployment.spec.template.spec.serviceAccountName }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: {{ (index .Values.cyber.deployment.spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution 0).labelSelector.matchLabels.tier }}
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: {{ .Values.cyber.deployment.spec.template.spec.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.cyber.deployment.spec.template.spec.securityContext.runAsUser }}
        runAsGroup: {{ .Values.cyber.deployment.spec.template.spec.securityContext.runAsGroup }}
        fsGroup: {{ .Values.cyber.deployment.spec.template.spec.securityContext.fsGroup }}
      containers:
        - name: {{ .Values.cyber.deployment.spec.template.spec.containers.name }}
          image: {{ .Values.cyber.deployment.spec.template.spec.containers.image }}
          imagePullPolicy: {{ .Values.cyber.deployment.spec.template.spec.containers.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.cyber.deployment.spec.template.spec.containers.securityContext.allowPrivilegeEscalation }}
          ports:
            - containerPort: {{ .Values.cyber.deployment.spec.template.spec.containers.ports.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.cyber.deployment.spec.template.spec.containers.resources.requests.cpu }}
              memory: {{ .Values.cyber.deployment.spec.template.spec.containers.resources.requests.memory }}
            limits:
              cpu: {{ .Values.cyber.deployment.spec.template.spec.containers.resources.limits.cpu }}
              memory: {{ .Values.cyber.deployment.spec.template.spec.containers.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: {{ .Values.cyber.deployment.spec.template.spec.containers.readinessProbe.httpGet.path }}
              port: {{ .Values.cyber.deployment.spec.template.spec.containers.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.readinessProbe.timeoutSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.cyber.deployment.spec.template.spec.containers.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.cyber.deployment.spec.template.spec.containers.livenessProbe.timeoutSeconds }}
