apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.cyber.rollout.name }}
  namespace: {{ .Values.cyber.rollout.namespace }}
  labels:
    tier: {{ .Values.cyber.rollout.labels.tier | quote }}
    prod: {{ .Values.cyber.rollout.labels.prod | quote }}
  annotations:
    "prometheus.io/scrape": {{ index .Values.cyber.rollout.annotations "prometheus.io/scrape" | quote }}
    "prometheus.io/path": {{ index .Values.cyber.rollout.annotations "prometheus.io/path" | quote }}
    "prometheus.io/port": {{ index .Values.cyber.rollout.annotations "prometheus.io/port" | quote }}
spec:
  replicas: {{ .Values.cyber.rollout.spec.replicas }}
  strategy:
    canary:
      steps:
{{ toYaml .Values.cyber.rollout.spec.canarySteps | indent 8 }}
  selector:
    matchLabels:
      tier: {{ .Values.cyber.rollout.spec.selector.matchLabels.tier }}
  template:
    metadata:
      labels:
        tier: {{ .Values.cyber.rollout.spec.template.metadata.labels.tier }}
    spec:
      serviceAccountName: {{ .Values.cyber.rollout.spec.template.spec.serviceAccountName }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: {{ (index .Values.cyber.rollout.spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution 0).labelSelector.matchLabels.tier }}
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: {{ .Values.cyber.rollout.spec.template.spec.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.cyber.rollout.spec.template.spec.securityContext.runAsUser }}
        runAsGroup: {{ .Values.cyber.rollout.spec.template.spec.securityContext.runAsGroup }}
        fsGroup: {{ .Values.cyber.rollout.spec.template.spec.securityContext.fsGroup }}
      containers:
{{- range .Values.cyber.rollout.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .securityContext.readOnlyRootFilesystem }}
          ports:
            - containerPort: {{ (index .ports 0).containerPort }}
          volumeMounts: 
{{- range .volumeMounts }} 
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
{{- end }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: {{ .readinessProbe.httpGet.path }}
              port: {{ .readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ .livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
      volumes:
{{- range .Values.cyber.rollout.spec.template.spec.volumes }}
  - name: {{ .name }}
    emptyDir: {}
{{- end }}
