apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.cyber.horizontalPodAutoscaler.name }}
  namespace: {{ .Values.cyber.horizontalPodAutoscaler.namespace }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.cyber.horizontalPodAutoscaler.spec.scaleTargetRef.apiVersion }}
    kind: {{ .Values.cyber.horizontalPodAutoscaler.spec.scaleTargetRef.kind }}
    name: {{ .Values.cyber.horizontalPodAutoscaler.spec.scaleTargetRef.name }}
  minReplicas: {{ .Values.cyber.horizontalPodAutoscaler.spec.minReplicas }}
  maxReplicas: {{ .Values.cyber.horizontalPodAutoscaler.spec.maxReplicas }}
  {{- $metric := index .Values.cyber.horizontalPodAutoscaler.spec.metrics 0 }}
  metrics:
    - type: Resource        
      resource:
        name: {{ $metric.resource.name }}
        target:
          type: Utilization
          averageUtilization: {{ $metric.resource.target.averageUtilization }}
