apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: {{ .Values.cyber.role.name }}
  namespace: {{ .Values.cyber.role.namespace }}
rules: 
  - apiGroups: {{ .Values.cyber.role.rules.apiGroups }}
    resources: {{ .Values.cyber.role.rules.resources }}
    verbs: {{ .Values.cyber.role.rules.verbs }}
