apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sast.persistentVolumeClaim.name }}
  namespace: {{ .Values.sast.persistentVolumeClaim.namespace }}
spec:
  storageClassName: {{ .Values.sast.persistentVolumeClaim.spec.storageClassName }}
  volumeName: {{ .Values.sast.persistentVolumeClaim.spec.volumeName }}
  accessModes:
    - {{ .Values.sast.persistentVolumeClaim.spec.accessModes 0 }}
  resources:
    requests:
      storage: {{ .Values.sast.persistentVolumeClaim.spec.resources.requests.storage }}