apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sast.deployment.name }}
  namespace: {{ .Values.sast.deployment.namespace }}
  labels:
    tier: {{ .Values.sast.deployment.labels.tier }}
    prod: {{ .Values.sast.deployment.labels.prod | quote }}
  annotations:
    "prometheus.io/scrape": {{ index .Values.sast.deployment.annotations "prometheus.io/scrape" | quote }}
    "prometheus.io/path": {{ index .Values.sast.deployment.annotations "prometheus.io/path" | quote }}
    "prometheus.io/port": {{ index .Values.sast.deployment.annotations "prometheus.io/port" | quote }}
spec:
  replicas: {{ .Values.sast.deployment.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.sast.deployment.spec.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.sast.deployment.spec.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      tier: {{ .Values.sast.deployment.spec.selector.matchLabels.tier }}
  template:
    metadata:
      labels:
        tier: {{ .Values.sast.deployment.spec.template.labels.tier }}
    spec:
      serviceAccountName: {{ .Values.sast.deployment.spec.template.spec.serviceAccountName }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: {{ (index .Values.sast.deployment.spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution 0).labelSelector.matchLabels.tier }}
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: {{ .Values.sast.deployment.spec.template.spec.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.sast.deployment.spec.template.spec.securityContext.runAsUser }}
        runAsGroup: {{ .Values.sast.deployment.spec.template.spec.securityContext.runAsGroup }}
        fsGroup: {{ .Values.sast.deployment.spec.template.spec.securityContext.fsGroup }}
      containers:
{{- range .Values.sast.deployment.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .securityContext.readOnlyRootFilesystem }}
          ports:
            - containerPort: {{ (index .ports 0).containerPort }}
          volumeMounts:
{{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
{{- end }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: {{ .readinessProbe.httpGet.path }}
              port: {{ .readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ .livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
{{- end }}
      volumes:
{{- range .Values.sast.deployment.spec.template.spec.volumes }}
        - name: {{ .name }}
          emptyDir: {}
{{- end }}