apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.sast.persistentVolume.name }}
spec:
  storageClassName: {{ .Values.sast.persistentVolume.spec.storageClassName }}
  persistentVolumeReclaimPolicy: {{ .Values.sast.persistentVolume.spec.persistentVolumeReclaimPolicy }}
  capacity:
    storage: {{ .Values.sast.persistentVolume.spec.capacity.storage }}
  accessModes:
    - {{ .Values.sast.persistentVolume.spec.accessModes 0 }}
  hostPath:
    path: {{ .Values.sast.persistentVolume.spec.hostPath.path }}
