apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.persistentVolumeClaim.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.spec.storageClassName }}
  volumeName: {{ .Values.persistentVolumeClaim.spec.volumeName }}
  accessModes:
    {{ .Values.persistentVolumeClaim.spec.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.spec.resources.requests.storage }}