apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sast.frontend.service.name }}
  namespace: {{ .Values.sast.frontend.service.namespace }}
spec:
  selector:
    tier: {{ .Values.sast.frontend.service.spec.selector.tier }}
  {{- $port := index .Values.sast.frontend.service.spec.ports 0 }}
  ports:
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol | default "TCP" }}
