apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.sast.role.name }}
  namespace: {{ .Values.sast.role.namespace }}
rules:
  - apiGroups: {{ .Values.sast.role.rules.apiGroups }}
    resources: {{ .Values.sast.role.rules.resources }}
    verbs: {{ .Values.sast.role.rules.verbs }}
