apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.sast.persistentVolume.name }}
spec:
  persistentVolumeReclaimPolicy: {{ .Values.sast.persistentVolume.spec.persistentVolumeReclaimPolicy }}
  capacity:
    storage: {{ .Values.sast.persistentVolume.spec.capacity.storage }}
  accessModes:
    {{ .Values.sast.persistentVolume.spec.accessModes }}
  hostPath:
    path: {{ .Values.sast.persistentVolume.spec.hostPath.path }}
