apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    tier: {{ .Values.service.spec.selector.tier }}
  ports:
    - port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
      protocol: {{ .Values.service.spec.ports.protocol | default "TCP" }}