apiVersion: v1 
kind: Secret 
metadata: 
    name: {{ .Values.vuln.secret.name }}
    namespace: {{ .Values.vuln.secret.namespace }} 
type: Opaque 
stringData: 
    DEEPSEEK_API_KEY: {{ .Values.vuln.secret.stringData.DEEPSEEK_API_KEY | quote }}