apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.vuln.networkPolicy.name }}
  namespace: {{ .Values.vuln.networkPolicy.namespace }}
spec:
  podSelector:
    matchLabels:
      tier: {{ .Values.vuln.networkPolicy.spec.podSelector.matchLabels.tier }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.vuln.networkPolicy.spec.ingress }}
    - from:
        {{- range .from }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    {{- range .Values.vuln.networkPolicy.spec.egress }}
    - to:
        {{- range .to }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}