apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.horizontalPodAutoscaler.name }}
  namespace: {{ .Values.horizontalPodAutoscaler.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.horizontalPodAutoscaler.spec.scaleTargetRef.name }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.spec.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.spec.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.horizontalPodAutoscaler.spec.metrics.resource.name }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.spec.metrics.resource.target.averageUtilization }}
