apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.vuln.deployment.name }}
  namespace: {{ .Values.vuln.deployment.namespace }}
  labels: 
    prod: {{ .Values.vuln.deployment.labels.prod }}
    tier: {{ .Values.vuln.deployment.labels.tier  }}
  annotations: 
    "prometheus.io/scrape": {{ index .Values.vuln.deployment.annotations "prometheus.io/scrape" | quote }}
    "prometheus.io/port": {{ index .Values.vuln.deployment.annotations "prometheus.io/port" | quote }}
spec: 
  replicas: {{ .Values.vuln.deployment.spec.replicas }}
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: {{ .Values.vuln.deployment.spec.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.vuln.deployment.spec.strategy.rollingUpdate.maxUnavailable }}
  selector: 
    matchLabels: 
      tier: {{ .Values.vuln.deployment.spec.selector.matchLabels.tier }}
  template: 
    metadata: 
      labels: 
        tier: {{ .Values.vuln.deployment.spec.template.metadata.labels.tier }}
    spec: 
      priorityClassName: {{ .Values.vuln.deployment.spec.template.spec.priorityClassName }}
      serviceAccountName: {{ .Values.vuln.deployment.spec.template.spec.serviceAccountName }}
      affinity:   
        podAntiAffinity:       
          requiredDuringSchedulingIgnoredDuringExecution: 
            - labelSelector: 
                matchLabels: 
                  tier: {{ (index .Values.vuln.deployment.spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution 0).labelSelector.matchLabels.tier }}
              topologyKey: "kubernetes.io/hostname" 
      securityContext: 
        runAsNonRoot:  {{ .Values.vuln.deployment.spec.template.spec.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.vuln.deployment.spec.template.spec.securityContext.runAsUser }}
        runAsGroup: {{ .Values.vuln.deployment.spec.template.spec.securityContext.runAsGroup }}
        fsGroup: {{ .Values.vuln.deployment.spec.template.spec.securityContext.fsGroup }}
      containers:
{{- range .Values.vuln.deployment.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          securityContext: 
            allowPrivilegeEscalation: {{ .securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .securityContext.readOnlyRootFilesystem }}
          ports: 
            - containerPort: {{ (index .ports 0).containerPort }}
          envFrom: 
            - secretRef: 
                name: {{ (index .envFrom 0).secretRef.name }}
          resources: 
            requests: 
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits: 
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          readinessProbe: 
            httpGet: 
              path: {{ .readinessProbe.httpGet.path }}
              port: {{ .readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
          livenessProbe: 
            tcpSocket: 
              port: {{ .livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds}}
{{- end }}