apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: {{ .Values.vuln.role.name }}
  namespace: {{ .Values.vuln.role.namespace }}
rules:
{{- range .Values.vuln.role.rules }}
  - apiGroups: {{ .apiGroups }}
    resources: {{ .resources }}
    verbs: {{ .verbs }}
{{- end }}