apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.vuln.networkPolicy.name }}
  namespace: {{ .Values.vuln.networkPolicy.namespace }}
spec:
  podSelector:
    matchLabels:
      tier: {{ .Values.vuln.networkPolicy.podSelector.tier }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: {{ .Values.vuln.networkPolicy.ingress.ipBlock.cidr }}
      ports:
        {{- range .Values.vuln.networkPolicy.ingress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.vuln.networkPolicy.egress.ipBlock.cidr }}
      ports:
        {{- range .Values.vuln.networkPolicy.egress.ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}