apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.roleBinding.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.roleBinding.subjects.name }}
    namespace: {{ .Values.roleBinding.subjects.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.roleBinding.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
