apiVersion: v1
kind: ConfigMap
metadata:
  name: cyber-config-rds
  namespace: mustang
data:
  DB_HOST: "database-1.c0pogq0w8mxc.us-east-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PORT: "3306"
  DB_NAME: "mysql"
  #REDIS_HOST: "your-valkey-cluster.cache.amazonaws.com"
  #REDIS_PORT: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: cyber-secrets-rds
  namespace: mustang
type: Opaque
stringData:
  DB_PASSWORD: "JF2WGJIprAESx7jP8aPu"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyber
  namespace: mustang
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cyber-role
  namespace: mustang
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io", "networking.k8s.io", "autoscaling"]
    resources: ["pods", "replicasets", "deployments", "networkpolicies", "horizontalpodautoscalers", "verticalpodautoscalers", "configmaps"]
    verbs: ["get", "create", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cyber-rb
  namespace: mustang
subjects:
  - kind: ServiceAccount
    name: cyber
    namespace: mustang
roleRef:
  kind: Role
  name: cyber-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-dep
  namespace: mustang
  labels:
    tier: versace
    prod: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "5051"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: versace
  template:
    metadata:
      labels:
        tier: versace
    spec:
      serviceAccountName: cyber
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: versace
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: cyber-con
          image: furkhan2000/shark:cyber
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5051
          envFrom:
            - configMapRef:
                name: cyber-config-rds
            - secretRef:
                name: cyber-secrets-rds
          resources:
            requests:
              cpu: "250m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "650Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5051
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5051
            initialDelaySeconds: 8
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cyber-svc
  namespace: mustang
spec:
  selector:
    tier: versace
  ports:
    - port: 5051
      protocol: TCP
      targetPort: 5051
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cyber-np
  namespace: mustang
spec:
  podSelector:
    matchLabels:
      tier: versace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 5051
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cyber-hpa
  namespace: mustang
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cyber-dep
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
