apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vuln-ingress
  namespace: mustang
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /vuln(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: vuln-svc
                port:
                  number: 3000
          - path: /sast(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sast-svc
                port:
                  number: 5050
          - path: /cyber(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cyber-svc
                port:
                  number: 5051
