apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 32507
      hostPort: 32507
      protocol: TCP
  - role: worker
  - role: worker
